# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
    - 'Automation/selenium/**'

jobs:
  Define_ENV:
      runs-on: [ self-hosted ]
      # Map a step output to a job output
      outputs:
        envname: ${{ steps.step1.outputs.test }}
      steps:
        - name: Set env to develop
          if: endsWith(github.ref, 'develop')
          run: echo "Envname=DEV" >> $GITHUB_ENV
        - name: Set env to TEST
          if: endsWith(github.ref, '/TEST')
          run: echo "Envname=TEST" >> $GITHUB_ENV
        - name: Set env to INT
          if: endsWith(github.ref, '/INT')
          run: echo "Envname=INT" >> $GITHUB_ENV
        - name: Set env to Prod
          if: endsWith(github.ref, 'master')
          run: echo "Envname=PROD" >> $GITHUB_ENV
        - id: step1
          run: echo "::set-output name=test::${{ env.Envname }}"
  Build:
    needs: [ Define_ENV ]
    runs-on: [ self-hosted ]
    environment: 
      name: ${{ needs.Define_ENV.outputs.envname }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
          settings-path: ${{ github.workspace }}
          java-version: '11'
          distribution: 'adopt'
    - name: Check env
      run: echo ${{needs.Define_ENV.outputs.envname}}
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: Build with Maven
      working-directory: ./Automation/selenium/
      run: mvn clean install -DproxySet=true -DproxyHost=proxy-spc.rd.corpintra.net -DproxyPort=3128 -P CICD
    - name: check the folder
      run: find ./ |  grep jar
    - name: Get current datetime
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"
    - name: Publish the data to Artifectory
      run: |
       curl -u${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_TOKEN }} -T NICE_Automatic_Testset.jar "https://artifacts.i.mercedes-benz.com/artifactory/nice-generic-main-local/Testing/${{needs.Define_ENV.outputs.envname}}/NICE_TestAutomation_Selenium_${{ steps.date.outputs.date }}.jar"
      working-directory: ./Automation/selenium/build/

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
